Message:
  Gamemode_Change: '&aSeu modo de jogo foi alterado para %s!'
  Gamemode_Change_Player: '&aO modo de jogo de %s foi alterado para %s.'
  Gamemode_Invalid: '&cEste modo de jogo é inválido!'
  Gamemode_Same_Player: '&cVocê não pode alterar o modo de jogo de sí mesmo!'
  No_Permissions: '&cVocê não tem permissão para executar esse comando!'
  Incorect_Target: '&cEsse comando não pode ser executado aqui!'
  Feed_Max: '&cSua fome está cheia.'
  Feed_Satiated: '&aSua fome foi saciada com êxito.'
  Feed_Full_Player: '&cA fome deste jogador já está cheia.'
  Feed_Regenerated_Player: '&eFome de &f%s &efoi saciada com êxito.'
  Feed_Regenerated_By_Player: '&eSua fome foi saciada por &f%s&e.'
  Maintence_Kick: '&cOlá %s você infelizemente foi kickado!'
  Website: '&aO site do nosso servidor é &fwww.seusite.com.br'
  Clear_Chat: '&aO chat foi limpo por &2%s&a!'
  Trash_Title: '&8Lixeira de %s.'
